from envs.gym.envs.toy_text.blackjack import BlackjackEnv
from envs.gym.envs.toy_text.roulette import RouletteEnv
from envs.gym.envs.toy_text.frozen_lake import FrozenLakeEnv
from envs.gym.envs.toy_text.nchain import NChainEnv
from envs.gym.envs.toy_text.hotter_colder import HotterColder
from envs.gym.envs.toy_text.guessing_game import GuessingGame
from envs.gym.envs.toy_text.kellycoinflip import KellyCoinflipEnv
from envs.gym.envs.toy_text.kellycoinflip import KellyCoinflipGeneralizedEnv
from envs.gym.envs.toy_text.cliffwalking import CliffWalkingEnv
from envs.gym.envs.toy_text.taxi import TaxiEnv
from envs.gym.envs.toy_text.guessing_game import GuessingGame
from envs.gym.envs.toy_text.hotter_colder import HotterColder
